import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CS-IP
 */
public class SHOEfACTORY extends javax.swing.JFrame {
    int amount,qty,amount1,amount2,amount3;

    /**
     * Creates new form SHOEfACTORY
     */
    public SHOEfACTORY() {
        initComponents();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        shoebox = new javax.swing.JCheckBox();
        sandalbox = new javax.swing.JCheckBox();
        slipperbox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        qty1 = new javax.swing.JTextField();
        qty2 = new javax.swing.JTextField();
        qty3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        shoeamt = new javax.swing.JTextField();
        sandalamt = new javax.swing.JTextField();
        slipperamt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        totalamt = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 460));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("SHOE FACTORY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 10, 266, 37);

        shoebox.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        shoebox.setForeground(new java.awt.Color(255, 255, 255));
        shoebox.setText("SHOE(CODE 101)");
        shoebox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shoebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoeboxActionPerformed(evt);
            }
        });
        getContentPane().add(shoebox);
        shoebox.setBounds(6, 97, 200, 31);

        sandalbox.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        sandalbox.setForeground(new java.awt.Color(255, 255, 255));
        sandalbox.setText("SANDAL(CODE 102)");
        sandalbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sandalbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sandalboxActionPerformed(evt);
            }
        });
        getContentPane().add(sandalbox);
        sandalbox.setBounds(6, 138, 230, 31);

        slipperbox.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        slipperbox.setForeground(new java.awt.Color(255, 255, 255));
        slipperbox.setText("SLIPPERS(CODE 103)");
        slipperbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slipperbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slipperboxActionPerformed(evt);
            }
        });
        getContentPane().add(slipperbox);
        slipperbox.setBounds(6, 177, 250, 31);

        jLabel2.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENTER QUANTITY");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(241, 61, 160, 16);

        qty1.setMinimumSize(new java.awt.Dimension(7, 7));
        getContentPane().add(qty1);
        qty1.setBounds(282, 97, 57, 30);
        getContentPane().add(qty2);
        qty2.setBounds(282, 137, 57, 30);

        qty3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty3ActionPerformed(evt);
            }
        });
        getContentPane().add(qty3);
        qty3.setBounds(282, 176, 57, 30);

        jLabel3.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AMOUNT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 57, 80, 24);
        getContentPane().add(shoeamt);
        shoeamt.setBounds(441, 95, 61, 30);
        getContentPane().add(sandalamt);
        sandalamt.setBounds(441, 136, 60, 30);
        getContentPane().add(slipperamt);
        slipperamt.setBounds(440, 176, 61, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 0));
        jButton1.setText("CALCULATE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 230, 173, 37);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 153));
        jButton2.setText("CLEAR");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 230, 111, 37);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 204));
        jButton3.setText("EXIT");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(390, 230, 91, 37);

        jLabel4.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOTAL AMOUNT");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 300, 150, 24);

        totalamt.setEditable(false);
        totalamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalamtActionPerformed(evt);
            }
        });
        getContentPane().add(totalamt);
        totalamt.setBounds(270, 300, 89, 24);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 204, 0));
        jButton4.setText("Back");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(270, 360, 90, 37);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/shoe (2).jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 640, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slipperboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slipperboxActionPerformed
        // TODO add your handling code here:
        
        if(qty3.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "First enter respective quantity.");
            slipperbox.setSelected(false);
        }
        else{qty=Integer.parseInt(qty3.getText());
         amount3=500*qty;
        slipperamt.setText(""+amount3);}
    }//GEN-LAST:event_slipperboxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        qty1.setText("");
        qty2.setText("");
        qty3.setText("");
        shoeamt.setText("");
        sandalamt.setText("");
        slipperamt.setText("");
        totalamt.setText("");
        shoebox.setSelected(false);
        sandalbox.setSelected(false);
        slipperbox.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void qty3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty3ActionPerformed

    private void shoeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoeboxActionPerformed
        // TODO add your handling code here:

        if(qty1.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "First enter respective quantity.");
            shoebox.setSelected(false);
        }
        else
        {qty=Integer.parseInt(qty1.getText());
         amount1=1500*qty;
        shoeamt.setText(""+amount1);}
    }//GEN-LAST:event_shoeboxActionPerformed

    private void sandalboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sandalboxActionPerformed
        // TODO add your handling code here:
        if(qty2.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "First enter respective quantity.");
            sandalbox.setSelected(false);
        } 
        
        else{qty=Integer.parseInt(qty2.getText());
         amount2=1000*qty;
        sandalamt.setText(""+amount2);}
    }//GEN-LAST:event_sandalboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //amount1=0; amount2=0;amount3=0;
        amount=amount1+amount2+amount3;
        totalamt.setText(""+amount);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void totalamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalamtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalamtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Options opt= new Options();
opt.setVisible(true);

setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SHOEfACTORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SHOEfACTORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SHOEfACTORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SHOEfACTORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SHOEfACTORY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField qty1;
    private javax.swing.JTextField qty2;
    private javax.swing.JTextField qty3;
    private javax.swing.JTextField sandalamt;
    private javax.swing.JCheckBox sandalbox;
    private javax.swing.JTextField shoeamt;
    private javax.swing.JCheckBox shoebox;
    private javax.swing.JTextField slipperamt;
    private javax.swing.JCheckBox slipperbox;
    private javax.swing.JTextField totalamt;
    // End of variables declaration//GEN-END:variables
}
